# https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
# production
# npx wrangler pages publish .svelte-kit/cloudflare --project-name=twind-run --branch=main
# preview
# npx wrangler pages publish .svelte-kit/cloudflare --project-name=twind-run --branch=next

name = "agent-run"

# https://developers.cloudflare.com/workers/platform/compatibility-dates/
compatibility_date = "2024-09-23"

# Also opt into an upcoming fix to the FormData API.
compatibility_flags = ["nodejs_compat_v2"   ]

[vars]
# https://developers.cloudflare.com/pages/platform/build-configuration/#language-support-and-tools
NODE_VERSION = "22"
